zone_lookup = {
    'qeynos': {'id': 1, 'long_name': 'South Qeynos', 'era': 'Old World', 'notes': ''},
    'qeynos2': {'id': 2, 'long_name': 'North Qeynos', 'era': 'Old World', 'notes': ''},
    'qrg': {'id': 3, 'long_name': 'Surefall Glade', 'era': 'Old World', 'notes': ''},
    'qeytoqrg': {'id': 4, 'long_name': 'Qeynos Hills', 'era': 'Old World', 'notes': ''},
    'highpass': {'id': 5, 'long_name': 'Highpass Hold', 'era': 'Old World', 'notes': ''},
    'highkeep': {'id': 6, 'long_name': 'Highpass Keep', 'era': 'Old World', 'notes': ''},
    'freportn': {'id': 8, 'long_name': 'North Freeport', 'era': 'Old World', 'notes': ''},
    'freportw': {'id': 9, 'long_name': 'West Freeport', 'era': 'Old World', 'notes': ''},
    'freporte': {'id': 10, 'long_name': 'East Freeport', 'era': 'Old World', 'notes': ''},
    'runnyeye': {'id': 11, 'long_name': 'Clan RunnyEye', 'era': 'Old World', 'notes': ''},
    'qey2hh1': {'id': 12, 'long_name': 'West Karana', 'era': 'Old World', 'notes': ''},
    'northkarana': {'id': 13, 'long_name': 'North Karana', 'era': 'Old World', 'notes': ''},
    'southkarana': {'id': 14, 'long_name': 'South Karana', 'era': 'Old World', 'notes': ''},
    'eastkarana': {'id': 15, 'long_name': 'East Karana', 'era': 'Old World', 'notes': ''},
    'beholder': {'id': 16, 'long_name': 'Gorge of King Xorbb', 'era': 'Old World', 'notes': ''},
    'blackburrow': {'id': 17, 'long_name': 'BlackBurrow', 'era': 'Old World', 'notes': ''},
    'paw': {'id': 18, 'long_name': 'Infected Paw', 'era': 'Old World', 'notes': ''},
    'rivervale': {'id': 19, 'long_name': 'Rivervale', 'era': 'Old World', 'notes': ''},
    'kithicor': {'id': 20, 'long_name': 'Kithicor Forest (A)', 'era': 'Old World', 'notes': ''},
    'commons': {'id': 21, 'long_name': 'West Commonlands', 'era': 'Old World', 'notes': ''},
    'ecommons': {'id': 22, 'long_name': 'East Commonlands', 'era': 'Old World', 'notes': ''},
    'erudnint': {'id': 23, 'long_name': 'Erudin Palace', 'era': 'Old World', 'notes': ''},
    'erudnext': {'id': 24, 'long_name': 'Erudin', 'era': 'Old World', 'notes': ''},
    'nektulos': {'id': 25, 'long_name': 'Nektulos Forest', 'era': 'Old World', 'notes': ''},
    'cshome': {'id': 26, 'long_name': 'Sunset Home', 'era': 'Old World', 'notes': ''},
    'lavastorm': {'id': 27, 'long_name': 'Lavastorm Mountains', 'era': 'Old World', 'notes': ''},
    'nektropos': {'id': 28, 'long_name': 'Nektropos', 'era': 'Old World', 'notes': ''},
    'halas': {'id': 29, 'long_name': 'Halas', 'era': 'Old World', 'notes': ''},
    'everfrost': {'id': 30, 'long_name': 'Everfrost Peaks', 'era': 'Old World', 'notes': ''},
    'soldunga': {'id': 31, 'long_name': 'Soluseks Eye', 'era': 'Old World', 'notes': ''},
    'soldungb': {'id': 32, 'long_name': 'Nagafens Lair', 'era': 'Old World', 'notes': ''},
    'misty': {'id': 33, 'long_name': 'Misty Thicket (A)', 'era': 'Old World', 'notes': ''},
    'nro': {'id': 34, 'long_name': 'North Ro (A)', 'era': 'Old World', 'notes': ''},
    'sro': {'id': 35, 'long_name': 'South Ro (A)', 'era': 'Old World', 'notes': ''},
    'befallen': {'id': 36, 'long_name': 'Befallen (A)', 'era': 'Old World', 'notes': ''},
    'oasis': {'id': 37, 'long_name': 'Oasis of Marr', 'era': 'Old World', 'notes': ''},
    'tox': {'id': 38, 'long_name': 'Toxxulia Forest', 'era': 'Old World', 'notes': ''},
    'hole': {'id': 39, 'long_name': 'The Ruins of Old Paineel', 'era': 'Old World', 'notes': ''},
    'neriaka': {'id': 40, 'long_name': 'Neriak Foreign Quarter', 'era': 'Old World', 'notes': ''},
    'neriakb': {'id': 41, 'long_name': 'Neriak Commons', 'era': 'Old World', 'notes': ''},
    'neriakc': {'id': 42, 'long_name': 'Neriak Third Gate', 'era': 'Old World', 'notes': ''},
    'neriakd': {'id': 43, 'long_name': 'Neriak Palace', 'era': 'Old World', 'notes': ''},
    'najena': {'id': 44, 'long_name': 'Najena', 'era': 'Old World', 'notes': ''},
    'qcat': {'id': 45, 'long_name': 'Qeynos Catacombs', 'era': 'Old World', 'notes': ''},
    'innothule': {'id': 46, 'long_name': 'Innothule Swamp (A)', 'era': 'Old World', 'notes': ''},
    'feerrott': {'id': 47, 'long_name': 'The Feerrott(A)', 'era': 'Old World', 'notes': ''},
    'cazicthule': {'id': 48, 'long_name': 'Cazic-Thule', 'era': 'Old World', 'notes': ''},
    'oggok': {'id': 49, 'long_name': 'Oggok', 'era': 'Old World', 'notes': ''},
    'rathemtn': {'id': 50, 'long_name': 'Mountains of Rathe', 'era': 'Old World', 'notes': ''},
    'lakerathe': {'id': 51, 'long_name': 'Lake Rathetear', 'era': 'Old World', 'notes': ''},
    'grobb': {'id': 52, 'long_name': 'Grobb', 'era': 'Old World', 'notes': ''},
    'aviak': {'id': 53, 'long_name': 'Aviak Village', 'era': 'Old World', 'notes': ''},
    'gfaydark': {'id': 54, 'long_name': 'The Greater Faydark', 'era': 'Old World', 'notes': ''},
    'akanon': {'id': 55, 'long_name': 'AkAnon', 'era': 'Old World', 'notes': ''},
    'steamfont': {'id': 56, 'long_name': 'Steamfont Mountains', 'era': 'Old World', 'notes': ''},
    'lfaydark': {'id': 57, 'long_name': 'The Lesser Faydark', 'era': 'Old World', 'notes': ''},
    'crushbone': {'id': 58, 'long_name': 'Clan Crushbone', 'era': 'Old World', 'notes': ''},
    'mistmoore': {'id': 59, 'long_name': 'Castle Mistmoore', 'era': 'Old World', 'notes': ''},
    'kaladima': {'id': 60, 'long_name': 'Kaladim (A)', 'era': 'Old World', 'notes': ''},
    'felwithea': {'id': 61, 'long_name': 'Felwithe (A)', 'era': 'Old World', 'notes': ''},
    'felwitheb': {'id': 62, 'long_name': 'Felwithe (B)', 'era': 'Old World', 'notes': ''},
    'unrest': {'id': 63, 'long_name': 'Estate of Unrest', 'era': 'Old World', 'notes': ''},
    'kedge': {'id': 64, 'long_name': 'Kedge Keep', 'era': 'Old World', 'notes': ''},
    'guktop': {'id': 65, 'long_name': 'Upper Guk', 'era': 'Old World', 'notes': ''},
    'gukbottom': {'id': 66, 'long_name': 'Lower Guk', 'era': 'Old World', 'notes': ''},
    'kaladimb': {'id': 67, 'long_name': 'Kaladim (B)', 'era': 'Old World', 'notes': ''},
    'butcher': {'id': 68, 'long_name': 'Butcherblock Mountains', 'era': 'Old World', 'notes': ''},
    'oot': {'id': 69, 'long_name': 'Ocean of Tears', 'era': 'Old World', 'notes': ''},
    'cauldron': {'id': 70, 'long_name': 'Dagnors Cauldron', 'era': 'Old World', 'notes': ''},
    'airplane': {'id': 71, 'long_name': 'Plane of Sky', 'era': 'Old World', 'notes': ''},
    'fearplane': {'id': 72, 'long_name': 'Plane of Fear', 'era': 'Old World', 'notes': ''},
    'permafrost': {'id': 73, 'long_name': 'Permafrost Keep', 'era': 'Old World', 'notes': ''},
    'kerraridge': {'id': 74, 'long_name': 'Kerra Isle', 'era': 'Old World', 'notes': ''},
    'paineel': {'id': 75, 'long_name': 'Paineel', 'era': 'Old World', 'notes': ''},
    'hateplane': {'id': 76, 'long_name': 'The Plane of Hate', 'era': 'Old World', 'notes': ''},
    'arena': {'id': 77, 'long_name': 'The Arena (A)', 'era': 'Old World', 'notes': ''},
    'fieldofbone': {'id': 78, 'long_name': 'The Field of Bone', 'era': 'Kunark', 'notes': ''},
    'warslikswood': {'id': 79, 'long_name': 'Warsliks Wood', 'era': 'Kunark', 'notes': ''},
    'soltemple': {'id': 80, 'long_name': 'Temple of Solusek Ro', 'era': 'Old World', 'notes': ''},
    'droga': {'id': 81, 'long_name': 'Temple of Droga', 'era': 'Kunark', 'notes': ''},
    'cabwest': {'id': 82, 'long_name': 'West Cabilis', 'era': 'Kunark', 'notes': ''},
    'swampofnohope': {'id': 83, 'long_name': 'Swamp of No Hope', 'era': 'Kunark', 'notes': ''},
    'firiona': {'id': 84, 'long_name': 'Firiona Vie', 'era': 'Kunark', 'notes': ''},
    'lakeofillomen': {'id': 85, 'long_name': 'Lake of Ill Omen', 'era': 'Kunark', 'notes': ''},
    'dreadlands': {'id': 86, 'long_name': 'Dreadlands', 'era': 'Kunark', 'notes': ''},
    'burningwood': {'id': 87, 'long_name': 'Burning Woods', 'era': 'Kunark', 'notes': ''},
    'kaesora': {'id': 88, 'long_name': 'Kaesora', 'era': 'Kunark', 'notes': ''},
    'sebilis': {'id': 89, 'long_name': 'Old Sebilis', 'era': 'Kunark', 'notes': ''},
    'citymist': {'id': 90, 'long_name': 'City of Mist', 'era': 'Kunark', 'notes': ''},
    'skyfire': {'id': 91, 'long_name': 'Skyfire Mountains', 'era': 'Kunark', 'notes': ''},
    'frontiermtns': {'id': 92, 'long_name': 'Frontier Mountains', 'era': 'Kunark', 'notes': ''},
    'overthere': {'id': 93, 'long_name': 'The Overthere', 'era': 'Kunark', 'notes': ''},
    'emeraldjungle': {'id': 94, 'long_name': 'The Emerald Jungle', 'era': 'Kunark', 'notes': ''},
    'trakanon': {'id': 95, 'long_name': 'Trakanons Teeth', 'era': 'Kunark', 'notes': ''},
    'timorous': {'id': 96, 'long_name': 'Timorous Deep', 'era': 'Kunark', 'notes': ''},
    'kurn': {'id': 97, 'long_name': 'Kurns Tower', 'era': 'Kunark', 'notes': ''},
    'erudsxing': {'id': 98, 'long_name': 'Eruds Crossing', 'era': 'Old World', 'notes': ''},
    'stonebrunt': {'id': 100, 'long_name': 'Stonebrunt Mountains', 'era': 'Old World', 'notes': ''},
    'warrens': {'id': 101, 'long_name': 'The Warrens', 'era': 'Old World', 'notes': ''},
    'karnor': {'id': 102, 'long_name': 'Karnors Castle', 'era': 'Kunark', 'notes': ''},
    'chardok': {'id': 103, 'long_name': 'Chardok', 'era': 'Kunark', 'notes': ''},
    'dalnir': {'id': 104, 'long_name': 'Dalnir', 'era': 'Kunark', 'notes': ''},
    'charasis': {'id': 105, 'long_name': 'Howling Stones', 'era': 'Kunark', 'notes': ''},
    'cabeast': {'id': 106, 'long_name': 'East Cabilis', 'era': 'Kunark', 'notes': ''},
    'nurga': {'id': 107, 'long_name': 'Mines of Nurga', 'era': 'Kunark', 'notes': ''},
    'veeshan': {'id': 108, 'long_name': 'Veeshans Peak', 'era': 'Kunark', 'notes': ''},
    'veksar': {'id': 109, 'long_name': 'Veksar', 'era': 'Kunark', 'notes': ''},
    'iceclad': {'id': 110, 'long_name': 'Iceclad Ocean', 'era': 'Velious', 'notes': ''},
    'frozenshadow': {'id': 111, 'long_name': 'Tower of Frozen Shadow', 'era': 'Velious', 'notes': ''},
    'velketor': {'id': 112, 'long_name': 'Velketors Labyrinth', 'era': 'Velious', 'notes': ''},
    'kael': {'id': 113, 'long_name': 'Kael Drakkal', 'era': 'Velious', 'notes': ''},
    'skyshrine': {'id': 114, 'long_name': 'Skyshrine', 'era': 'Velious', 'notes': ''},
    'thurgadina': {'id': 115, 'long_name': 'Thurgadin', 'era': 'Velious', 'notes': ''},
    'eastwastes': {'id': 116, 'long_name': 'Eastern Wastes', 'era': 'Velious', 'notes': ''},
    'cobaltscar': {'id': 117, 'long_name': 'Cobalt Scar', 'era': 'Velious', 'notes': ''},
    'greatdivide': {'id': 118, 'long_name': 'Great Divide', 'era': 'Velious', 'notes': ''},
    'wakening': {'id': 119, 'long_name': 'The Wakening Land', 'era': 'Velious', 'notes': ''},
    'westwastes': {'id': 120, 'long_name': 'Western Wastes', 'era': 'Velious', 'notes': ''},
    'crystal': {'id': 121, 'long_name': 'Crystal Caverns', 'era': 'Velious', 'notes': ''},
    'necropolis': {'id': 123, 'long_name': 'Dragon Necropolis', 'era': 'Velious', 'notes': ''},
    'templeveeshan': {'id': 124, 'long_name': 'Temple of Veeshan', 'era': 'Velious', 'notes': ''},
    'sirens': {'id': 125, 'long_name': 'Sirens Grotto', 'era': 'Velious', 'notes': ''},
    'mischiefplane': {'id': 126, 'long_name': 'Plane of Mischief', 'era': 'Velious', 'notes': ''},
    'growthplane': {'id': 127, 'long_name': 'Plane of Growth', 'era': 'Velious', 'notes': ''},
    'sleeper': {'id': 128, 'long_name': 'Sleepers Tomb', 'era': 'Velious', 'notes': ''},
    'thurgadinb': {'id': 129, 'long_name': 'Icewell Keep', 'era': 'Velious', 'notes': ''},
    'erudsxing2': {'id': 130, 'long_name': 'Marauders Mire', 'era': 'Old World', 'notes': ''},
    'shadowhaven': {'id': 150, 'long_name': 'Shadow Haven', 'era': 'Luclin', 'notes': ''},
    'bazaar': {'id': 151, 'long_name': 'The Bazaar', 'era': 'Luclin', 'notes': ''},
    'nexus': {'id': 152, 'long_name': 'The Nexus', 'era': 'Luclin', 'notes': ''},
    'echo': {'id': 153, 'long_name': 'Echo Caverns', 'era': 'Luclin', 'notes': ''},
    'acrylia': {'id': 154, 'long_name': 'Acrylia Caverns', 'era': 'Luclin', 'notes': ''},
    'sharvahl': {'id': 155, 'long_name': 'Shar Vahl', 'era': 'Luclin', 'notes': ''},
    'paludal': {'id': 156, 'long_name': 'Paludal Caverns', 'era': 'Luclin', 'notes': ''},
    'fungusgrove': {'id': 157, 'long_name': 'Fungus Grove', 'era': 'Luclin', 'notes': ''},
    'vexthal': {'id': 158, 'long_name': 'Vex Thal', 'era': 'Luclin', 'notes': ''},
    'sseru': {'id': 159, 'long_name': 'Sanctus Seru', 'era': 'Luclin', 'notes': ''},
    'katta': {'id': 160, 'long_name': 'Katta Castellum', 'era': 'Luclin', 'notes': ''},
    'netherbian': {'id': 161, 'long_name': 'Netherbian Lair', 'era': 'Luclin', 'notes': ''},
    'ssratemple': {'id': 162, 'long_name': 'Ssraeshza Temple', 'era': 'Luclin', 'notes': ''},
    'griegsend': {'id': 163, 'long_name': 'Griegs End', 'era': 'Luclin', 'notes': ''},
    'thedeep': {'id': 164, 'long_name': 'The Deep', 'era': 'Luclin', 'notes': ''},
    'shadeweaver': {'id': 165, 'long_name': 'Shadeweavers Thicket', 'era': 'Luclin', 'notes': ''},
    'hollowshade': {'id': 166, 'long_name': 'Hollowshade Moor', 'era': 'Luclin', 'notes': ''},
    'grimling': {'id': 167, 'long_name': 'Grimling Forest', 'era': 'Luclin', 'notes': ''},
    'mseru': {'id': 168, 'long_name': 'Marus Seru', 'era': 'Luclin', 'notes': ''},
    'letalis': {'id': 169, 'long_name': 'Mons Letalis', 'era': 'Luclin', 'notes': ''},
    'twilight': {'id': 170, 'long_name': 'The Twilight Sea', 'era': 'Luclin', 'notes': ''},
    'thegrey': {'id': 171, 'long_name': 'The Grey', 'era': 'Luclin', 'notes': ''},
    'tenebrous': {'id': 172, 'long_name': 'The Tenebrous Mountains', 'era': 'Luclin', 'notes': ''},
    'maiden': {'id': 173, 'long_name': 'The Maidens Eye', 'era': 'Luclin', 'notes': ''},
    'dawnshroud': {'id': 174, 'long_name': 'Dawnshroud Peaks', 'era': 'Luclin', 'notes': ''},
    'scarlet': {'id': 175, 'long_name': 'The Scarlet Desert', 'era': 'Luclin', 'notes': ''},
    'umbral': {'id': 176, 'long_name': 'The Umbral Plains', 'era': 'Luclin', 'notes': ''},
    'akheva': {'id': 179, 'long_name': 'Akheva Ruins', 'era': 'Luclin', 'notes': ''},
    'arena2': {'id': 180, 'long_name': 'The Arena (B)', 'era': 'Old World', 'notes': ''},
    'jaggedpine': {'id': 181, 'long_name': 'The Jaggedpine Forest', 'era': 'Old World', 'notes': ''},
    'nedaria': {'id': 182, 'long_name': 'Nedarias Landing', 'era': 'Old World', 'notes': ''},
    'tutorial': {'id': 183, 'long_name': 'Tutorial Zone', 'era': '', 'notes': ''},
    'hateplaneb': {'id': 186, 'long_name': 'The Plane of Hate', 'era': 'Old World', 'notes': ''},
    'shadowrest': {'id': 187, 'long_name': 'Shadowrest', 'era': '', 'notes': ''},
    'tutoriala': {'id': 188, 'long_name': 'The Mines of Gloomingdeep (A)', 'era': '', 'notes': ''},
    'tutorialb': {'id': 189, 'long_name': 'The Mines of Gloomingdeep (B)', 'era': '', 'notes': ''},
    'codecay': {'id': 200, 'long_name': 'Ruins of Lxanvom', 'era': 'Planes of Power', 'notes': ''},
    'pojustice': {'id': 201, 'long_name': 'Plane of Justice', 'era': 'Planes of Power', 'notes': ''},
    'poknowledge': {'id': 202, 'long_name': 'Plane of Knowledge', 'era': 'Planes of Power', 'notes': ''},
    'potranquility': {'id': 203, 'long_name': 'Plane of Tranquility', 'era': 'Planes of Power', 'notes': ''},
    'ponightmare': {'id': 204, 'long_name': 'Plane of Nightmare', 'era': 'Planes of Power', 'notes': ''},
    'podisease': {'id': 205, 'long_name': 'Plane of Disease', 'era': 'Planes of Power', 'notes': ''},
    'poinnovation': {'id': 206, 'long_name': 'Plane of Innovation', 'era': 'Planes of Power', 'notes': ''},
    'potorment': {'id': 207, 'long_name': 'Plane of Torment', 'era': 'Planes of Power', 'notes': ''},
    'povalor': {'id': 208, 'long_name': 'Plane of Valor', 'era': 'Planes of Power', 'notes': ''},
    'bothunder': {'id': 209, 'long_name': 'Torden, The Bastion of Thunder', 'era': 'Planes of Power', 'notes': ''},
    'postorms': {'id': 210, 'long_name': 'Plane of Storms', 'era': 'Planes of Power', 'notes': ''},
    'hohonora': {'id': 211, 'long_name': 'Halls of Honor', 'era': 'Planes of Power', 'notes': ''},
    'solrotower': {'id': 212, 'long_name': 'Solusek Ros Tower', 'era': 'Planes of Power', 'notes': ''},
    'powar': {'id': 213, 'long_name': 'Plane of War', 'era': 'Planes of Power', 'notes': ''},
    'potactics': {'id': 214, 'long_name': 'Drunder, Fortress of Zek', 'era': 'Planes of Power', 'notes': ''},
    'poair': {'id': 215, 'long_name': 'Eryslai, the Kingdom of Wind', 'era': 'Planes of Power', 'notes': ''},
    'powater': {'id': 216, 'long_name': 'Reef of Coirnav', 'era': 'Planes of Power', 'notes': ''},
    'pofire': {'id': 217, 'long_name': 'Doomfire, The Burning Lands', 'era': 'Planes of Power', 'notes': ''},
    'poeartha': {'id': 218, 'long_name': 'Vegarlson, The Earthen Badlands', 'era': 'Planes of Power', 'notes': ''},
    'potimea': {'id': 219, 'long_name': 'Plane of Time (A)', 'era': 'Planes of Power', 'notes': ''},
    'hohonorb': {'id': 220, 'long_name': 'Temple of Marr (A)', 'era': 'Planes of Power', 'notes': ''},
    'nightmareb': {'id': 221, 'long_name': 'Lair of Terris Thule', 'era': 'Planes of Power', 'notes': ''},
    'poearthb': {'id': 222, 'long_name': 'Stronghold of the Twelve', 'era': 'Planes of Power', 'notes': ''},
    'potimeb': {'id': 223, 'long_name': 'Plane of Time (B)', 'era': 'Planes of Power', 'notes': ''},
    'gunthak': {'id': 224, 'long_name': 'Gulf of Gunthak', 'era': 'Legacy of Ykesha', 'notes': ''},
    'dulak': {'id': 225, 'long_name': 'Dulaks Harbor', 'era': 'Legacy of Ykesha', 'notes': ''},
    'torgiran': {'id': 226, 'long_name': 'Torgiran Mines', 'era': 'Legacy of Ykesha', 'notes': ''},
    'nadox': {'id': 227, 'long_name': 'Crypt of Nadox', 'era': 'Legacy of Ykesha', 'notes': ''},
    'hatesfury': {'id': 228, 'long_name': 'Hates Fury, The Scorned Maiden', 'era': 'Legacy of Ykesha', 'notes': ''},
    'guka': {'id': 229, 'long_name': 'The Cauldron of Lost Souls', 'era': 'LDoN', 'notes': ''},
    'ruja': {'id': 230, 'long_name': 'The Bloodied Quarries', 'era': 'LDoN', 'notes': ''},
    'taka': {'id': 231, 'long_name': 'The Sunken Library', 'era': 'LDoN', 'notes': ''},
    'mira': {'id': 232, 'long_name': 'The Silent Gallery', 'era': 'LDoN', 'notes': ''},
    'mmca': {'id': 233, 'long_name': 'The Forlorn Caverns', 'era': 'LDoN', 'notes': ''},
    'gukb': {'id': 234, 'long_name': 'The Drowning Crypt', 'era': 'LDoN', 'notes': ''},
    'rujb': {'id': 235, 'long_name': 'The Halls of War', 'era': 'LDoN', 'notes': ''},
    'takb': {'id': 236, 'long_name': 'The Shifting Tower', 'era': 'LDoN', 'notes': ''},
    'mirb': {'id': 237, 'long_name': 'The Maw of the Menagerie', 'era': 'LDoN', 'notes': ''},
    'mmcb': {'id': 238, 'long_name': 'The Dreary Grotto', 'era': 'LDoN', 'notes': ''},
    'gukc': {'id': 239, 'long_name': 'The Ancient Aqueducts', 'era': 'LDoN', 'notes': ''},
    'rujc': {'id': 240, 'long_name': 'The Wind Bridges', 'era': 'LDoN', 'notes': ''},
    'takc': {'id': 241, 'long_name': 'The Fading Temple', 'era': 'LDoN', 'notes': ''},
    'mirc': {'id': 242, 'long_name': 'The Spider Den', 'era': 'LDoN', 'notes': ''},
    'mmcc': {'id': 243, 'long_name': 'The Asylum of Invoked Stone', 'era': 'LDoN', 'notes': ''},
    'gukd': {'id': 244, 'long_name': 'The Mushroom Grove', 'era': 'LDoN', 'notes': ''},
    'rujd': {'id': 245, 'long_name': 'The Gladiator Pits', 'era': 'LDoN', 'notes': ''},
    'takd': {'id': 246, 'long_name': 'The Royal Observatory', 'era': 'LDoN', 'notes': ''},
    'mird': {'id': 247, 'long_name': 'The Hushed Banquet', 'era': 'LDoN', 'notes': ''},
    'mmcd': {'id': 248, 'long_name': 'The Chambers of Eternal Affliction', 'era': 'LDoN', 'notes': ''},
    'guke': {'id': 249, 'long_name': 'The Foreboding Prison', 'era': 'LDoN', 'notes': ''},
    'ruje': {'id': 250, 'long_name': 'The Drudge Hollows', 'era': 'LDoN', 'notes': ''},
    'take': {'id': 251, 'long_name': 'The River of Recollection', 'era': 'LDoN', 'notes': ''},
    'mire': {'id': 252, 'long_name': 'The Frosted Halls', 'era': 'LDoN', 'notes': ''},
    'mmce': {'id': 253, 'long_name': 'The Sepulcher of the Damned', 'era': 'LDoN', 'notes': ''},
    'gukf': {'id': 254, 'long_name': 'The Chapel of the Witnesses', 'era': 'LDoN', 'notes': ''},
    'rujf': {'id': 255, 'long_name': 'The Fortified Lair of the Taskmasters', 'era': 'LDoN', 'notes': ''},
    'takf': {'id': 256, 'long_name': 'The Sandfall Corridors', 'era': 'LDoN', 'notes': ''},
    'mirf': {'id': 257, 'long_name': 'The Forgotten Wastes', 'era': 'LDoN', 'notes': ''},
    'mmcf': {'id': 258, 'long_name': 'The Ritualistic Summoning Grounds', 'era': 'LDoN', 'notes': ''},
    'gukg': {'id': 259, 'long_name': 'The Root Garden', 'era': 'LDoN', 'notes': ''},
    'rujg': {'id': 260, 'long_name': 'The Hidden Vale', 'era': 'LDoN', 'notes': ''},
    'takg': {'id': 261, 'long_name': 'The Balancing Chamber', 'era': 'LDoN', 'notes': ''},
    'mirg': {'id': 262, 'long_name': 'The Heart of the Menagerie', 'era': 'LDoN', 'notes': ''},
    'mmcg': {'id': 263, 'long_name': 'The Cesspits of Putrescence', 'era': 'LDoN', 'notes': ''},
    'gukh': {'id': 264, 'long_name': 'The Accursed Sanctuary', 'era': 'LDoN', 'notes': ''},
    'rujh': {'id': 265, 'long_name': 'The Blazing Forge', 'era': 'LDoN', 'notes': ''},
    'takh': {'id': 266, 'long_name': 'The Sweeping Tides', 'era': 'LDoN', 'notes': ''},
    'mirh': {'id': 267, 'long_name': 'The Morbid Laboratory', 'era': 'LDoN', 'notes': ''},
    'mmch': {'id': 268, 'long_name': 'The Aisles of Blood', 'era': 'LDoN', 'notes': ''},
    'ruji': {'id': 269, 'long_name': 'The Arena of Chance', 'era': 'LDoN', 'notes': ''},
    'taki': {'id': 270, 'long_name': 'The Antiquated Palace', 'era': 'LDoN', 'notes': ''},
    'miri': {'id': 271, 'long_name': 'The Theater of Imprisoned Horrors', 'era': 'LDoN', 'notes': ''},
    'mmci': {'id': 272, 'long_name': 'The Halls of Sanguinary Rites', 'era': 'LDoN', 'notes': ''},
    'rujj': {'id': 273, 'long_name': 'The Barracks of War', 'era': 'LDoN', 'notes': ''},
    'takj': {'id': 274, 'long_name': 'The Prismatic Corridors', 'era': 'LDoN', 'notes': ''},
    'mirj': {'id': 275, 'long_name': 'The Grand Library', 'era': 'LDoN', 'notes': ''},
    'mmcj': {'id': 276, 'long_name': 'The Infernal Sanctuary', 'era': 'LDoN', 'notes': ''},
    'chardokb': {'id': 277, 'long_name': 'The Halls of Betrayal', 'era': 'Kunark', 'notes': ''},
    'soldungc': {'id': 278, 'long_name': 'The Caverns of Exile', 'era': 'Old World', 'notes': ''},
    'abysmal': {'id': 279, 'long_name': 'Abysmal Sea', 'era': 'Gates of Discord', 'notes': ''},
    'natimbi': {'id': 280, 'long_name': 'Natimbi, The Broken Shores', 'era': 'Gates of Discord', 'notes': ''},
    'qinimi': {'id': 281, 'long_name': 'Qinimi, Court of Nihilia', 'era': 'Gates of Discord', 'notes': ''},
    'riwwi': {'id': 282, 'long_name': 'Riwwi, Coliseum of Games', 'era': 'Gates of Discord', 'notes': ''},
    'barindu': {'id': 283, 'long_name': 'Barindu, Hanging Gardens', 'era': 'Gates of Discord', 'notes': ''},
    'ferubi': {'id': 284, 'long_name': 'Ferubi, Forgotten Temple of Taelosia', 'era': 'Gates of Discord', 'notes': ''},
    'snpool': {'id': 285, 'long_name': 'Sewers of Nihilia, Pool of Sludge', 'era': 'Gates of Discord', 'notes': ''},
    'snlair': {'id': 286, 'long_name': 'Sewers of Nihilia, Lair of Trapped Ones', 'era': 'Gates of Discord', 'notes': ''},
    'snplant': {'id': 287, 'long_name': 'Sewers of Nihilia, Purifying Plant', 'era': 'Gates of Discord', 'notes': ''},
    'sncrematory': {'id': 288, 'long_name': 'Sewers of Nihilia, the Crematory', 'era': 'Gates of Discord', 'notes': ''},
    'tipt': {'id': 289, 'long_name': 'Tipt, Treacherous Crags', 'era': 'Gates of Discord', 'notes': ''},
    'vxed': {'id': 290, 'long_name': 'Vxed, The Crumbling Caverns', 'era': 'Gates of Discord', 'notes': ''},
    'yxtta': {'id': 291, 'long_name': 'Yxtta, Pulpit of Exiles', 'era': 'Gates of Discord', 'notes': ''},
    'uqua': {'id': 292, 'long_name': 'Uqua, The Ocean God Chantry', 'era': 'Gates of Discord', 'notes': ''},
    'kodtaz': {'id': 293, 'long_name': 'KodTaz, Broken Trial Grounds', 'era': 'Gates of Discord', 'notes': ''},
    'ikkinz': {'id': 294, 'long_name': 'Ikkinz, Chambers of Destruction', 'era': 'Gates of Discord', 'notes': ''},
    'qvic': {'id': 295, 'long_name': 'Qvic, Prayer Grounds of Calling', 'era': 'Gates of Discord', 'notes': ''},
    'inktuta': {'id': 296, 'long_name': 'InktuTa, The Unmasked Chapel', 'era': 'Gates of Discord', 'notes': ''},
    'txevu': {'id': 297, 'long_name': 'Txevu, Lair of the Elite', 'era': 'Gates of Discord', 'notes': ''},
    'tacvi': {'id': 298, 'long_name': 'Tacvi, Seat of the Slaver', 'era': 'Gates of Discord', 'notes': ''},
    'qvicb': {'id': 299, 'long_name': 'Qvic, the Hidden Vault', 'era': 'Gates of Discord', 'notes': ''},
    'wallofslaughter': {'id': 300, 'long_name': 'Wall of Slaughter', 'era': 'Omens of War', 'notes': ''},
    'bloodfields': {'id': 301, 'long_name': 'The Bloodfields', 'era': 'Omens of War', 'notes': ''},
    'draniksscar': {'id': 302, 'long_name': 'Draniks Scar', 'era': 'Omens of War', 'notes': ''},
    'causeway': {'id': 303, 'long_name': 'Nobles Causeway', 'era': 'Omens of War', 'notes': ''},
    'chambersa': {'id': 304, 'long_name': 'Muramite Proving Grounds (A)', 'era': 'Omens of War', 'notes': ''},
    'chambersb': {'id': 305, 'long_name': 'Muramite Proving Grounds (B)', 'era': 'Omens of War', 'notes': ''},
    'chambersc': {'id': 306, 'long_name': 'Muramite Proving Grounds (C)', 'era': 'Omens of War', 'notes': ''},
    'chambersd': {'id': 307, 'long_name': 'Muramite Proving Grounds (D)', 'era': 'Omens of War', 'notes': ''},
    'chamberse': {'id': 308, 'long_name': 'Muramite Proving Grounds (E)', 'era': 'Omens of War', 'notes': ''},
    'chambersf': {'id': 309, 'long_name': 'Muramite Proving Grounds (F)', 'era': 'Omens of War', 'notes': ''},
    'provinggrounds': {'id': 316, 'long_name': 'Muramite Proving Grounds', 'era': 'Omens of War', 'notes': ''},
    'anguish': {'id': 317, 'long_name': 'Asylum of Anguish', 'era': 'Omens of War', 'notes': ''},
    'dranikhollowsa': {'id': 318, 'long_name': 'Draniks Hollows (A)', 'era': 'Omens of War', 'notes': ''},
    'dranikhollowsb': {'id': 319, 'long_name': 'Draniks Hollows (B)', 'era': 'Omens of War', 'notes': ''},
    'dranikhollowsc': {'id': 320, 'long_name': 'Draniks Hollows (C)', 'era': 'Omens of War', 'notes': ''},
    'dranikhollowsd': {'id': 321, 'long_name': 'Draniks Hollows (D)', 'era': 'Omens of War', 'notes': ''},
    'dranikhollowse': {'id': 322, 'long_name': 'Draniks Hollows (E)', 'era': 'Omens of War', 'notes': ''},
    'dranikhollowsf': {'id': 323, 'long_name': 'Draniks Hollows (F)', 'era': 'Omens of War', 'notes': ''},
    'dranikhollowsg': {'id': 324, 'long_name': 'Draniks Hollows (G)', 'era': 'Omens of War', 'notes': ''},
    'dranikhollowsh': {'id': 325, 'long_name': 'Draniks Hollows (H)', 'era': 'Omens of War', 'notes': ''},
    'dranikhollowsi': {'id': 326, 'long_name': 'Draniks Hollows (I)', 'era': 'Omens of War', 'notes': ''},
    'dranikhollowsj': {'id': 327, 'long_name': 'Draniks Hollows (J)', 'era': 'Omens of War', 'notes': ''},
    'dranikcatacombsa': {'id': 328, 'long_name': 'Catacombs of Dranik (A)', 'era': 'Omens of War', 'notes': ''},
    'dranikcatacombsb': {'id': 329, 'long_name': 'Catacombs of Dranik (B)', 'era': 'Omens of War', 'notes': ''},
    'dranikcatacombsc': {'id': 330, 'long_name': 'Catacombs of Dranik (C)', 'era': 'Omens of War', 'notes': ''},
    'draniksewersa': {'id': 331, 'long_name': 'Sewers of Dranik (A)', 'era': 'Omens of War', 'notes': ''},
    'draniksewersb': {'id': 332, 'long_name': 'Sewers of Dranik (B)', 'era': 'Omens of War', 'notes': ''},
    'draniksewersc': {'id': 333, 'long_name': 'Sewers of Dranik (C)', 'era': 'Omens of War', 'notes': ''},
    'riftseekers': {'id': 334, 'long_name': 'Riftseekers Sanctum', 'era': 'Omens of War', 'notes': ''},
    'harbingers': {'id': 335, 'long_name': 'Harbingers Spire', 'era': 'Omens of War', 'notes': ''},
    'dranik': {'id': 336, 'long_name': 'The Ruined City of Dranik', 'era': 'Omens of War', 'notes': ''},
    'broodlands': {'id': 337, 'long_name': 'The Broodlands', 'era': 'Dragons of Norrath', 'notes': ''},
    'stillmoona': {'id': 338, 'long_name': 'Stillmoon Temple', 'era': 'Dragons of Norath', 'notes': ''},
    'stillmoonb': {'id': 339, 'long_name': 'The Ascent', 'era': 'Dragons of Norrath', 'notes': ''},
    'thundercrest': {'id': 340, 'long_name': 'Thundercrest Isle', 'era': 'Dragons of Norrath', 'notes': 'Current Hub'},
    'delvea': {'id': 341, 'long_name': 'Lavaspinners Lair', 'era': 'Dragons of Norrath', 'notes': ''},
    'delveb': {'id': 342, 'long_name': 'Tirranuns Delve', 'era': 'Dragons of Norrath', 'notes': ''},
    'thenest': {'id': 343, 'long_name': 'The Accursed Nest', 'era': 'Dragons of Norrath', 'notes': ''},
    'guildlobby': {'id': 344, 'long_name': 'The Guild Lobby', 'era': 'Dragons of Norrath', 'notes': ''},
    'guildhall': {'id': 345, 'long_name': 'Guild Hall', 'era': 'Dragons of Norrath', 'notes': ''},
    'guildhalllrg': {'id': 346, 'long_name': 'Grand Guild Hall', 'era': 'Dragons of Norrath', 'notes': ''},
    'illsalin': {'id': 347, 'long_name': 'Ruins of Illsalin', 'era': 'Depths of Darkhollow', 'notes': ''},
    'illsalina': {'id': 348, 'long_name': 'Imperial Bazaar', 'era': 'Depths of Darkhollow', 'notes': ''},
    'illsalinb': {'id': 349, 'long_name': 'Temple of the Korlach', 'era': 'Depths of Darkhollow', 'notes': ''},
    'illsalinc': {'id': 350, 'long_name': 'The Nargilor Pits', 'era': 'Depths of Darkhollow', 'notes': ''},
    'dreadspire': {'id': 351, 'long_name': 'Dreadspire Keep', 'era': 'Depths of Darkhollow', 'notes': ''},
    'drachnidhive': {'id': 354, 'long_name': 'The Hive', 'era': 'Depths of Darkhollow', 'notes': ''},
    'drachnidhivea': {'id': 355, 'long_name': 'Living Larder', 'era': 'Depths of Darkhollow', 'notes': ''},
    'drachnidhiveb': {'id': 356, 'long_name': 'Coven of the Skinwalkers', 'era': 'Depths of Darkhollow', 'notes': ''},
    'drachnidhivec': {'id': 357, 'long_name': 'Queen Sendaiis Lair', 'era': 'Depths of Darkhollow', 'notes': ''},
    'westkorlach': {'id': 358, 'long_name': 'Stoneroot Falls', 'era': 'Depths of Darkhollow', 'notes': ''},
    'westkorlacha': {'id': 359, 'long_name': 'Chambers of Xill', 'era': 'Depths of Darkhollow', 'notes': ''},
    'westkorlachb': {'id': 360, 'long_name': 'Caverns of the Lost', 'era': 'Depths of Darkhollow', 'notes': ''},
    'westkorlachc': {'id': 361, 'long_name': 'Lair of the Korlach', 'era': 'Depths of Darkhollow', 'notes': ''},
    'eastkorlach': {'id': 362, 'long_name': 'Undershore', 'era': 'Depths of Darkhollow', 'notes': ''},
    'eastkorlacha': {'id': 363, 'long_name': 'Snarlstone Dens', 'era': 'Depths of Darkhollow', 'notes': ''},
    'shadowspine': {'id': 364, 'long_name': 'Shadowspine', 'era': 'Depths of Darkhollow', 'notes': ''},
    'corathus': {'id': 365, 'long_name': 'Corathus Creep', 'era': 'Depths of Darkhollow', 'notes': ''},
    'corathusa': {'id': 366, 'long_name': 'Sporali Caverns', 'era': 'Depths of Darkhollow', 'notes': ''},
    'corathusb': {'id': 367, 'long_name': 'Corathus Lair', 'era': 'Depths of Darkhollow', 'notes': ''},
    'nektulosa': {'id': 368, 'long_name': 'Shadowed Grove', 'era': 'Depths of Darkhollow', 'notes': ''},
    'arcstone': {'id': 369, 'long_name': 'Arcstone', 'era': 'Prophecy of Ro', 'notes': ''},
    'relic': {'id': 370, 'long_name': 'Relic', 'era': 'Prophecy of Ro', 'notes': ''},
    'skylance': {'id': 371, 'long_name': 'Skylance', 'era': 'Prophecy of Ro', 'notes': ''},
    'devastation': {'id': 372, 'long_name': 'The Devastation', 'era': 'Prophecy of Ro', 'notes': ''},
    'devastationa': {'id': 373, 'long_name': 'The Seething Wall', 'era': 'Prophecy of Ro', 'notes': ''},
    'rage': {'id': 374, 'long_name': 'Sverag, Stronghold of Rage', 'era': 'Prophecy of Ro', 'notes': ''},
    'ragea': {'id': 375, 'long_name': 'Razorthorn, Tower of Sullon Zek', 'era': 'Prophecy of Ro', 'notes': ''},
    'takishruins': {'id': 376, 'long_name': 'Ruins of Takish-Hiz', 'era': 'Prophecy of Ro', 'notes': ''},
    'takishruinsa': {'id': 377, 'long_name': 'The Root of Ro', 'era': 'Prophecy of Ro', 'notes': ''},
    'elddar': {'id': 378, 'long_name': 'The Elddar Forest', 'era': 'Prophecy of Ro', 'notes': ''},
    'elddara': {'id': 379, 'long_name': 'Tunares Shrine', 'era': 'Prophecy of Ro', 'notes': ''},
    'theater': {'id': 380, 'long_name': 'Theater of Blood', 'era': 'Prophecy of Ro', 'notes': ''},
    'theatera': {'id': 381, 'long_name': 'Deathknell, Tower of Dissonance', 'era': 'Prophecy of Ro', 'notes': ''},
    'freeporteast': {'id': 382, 'long_name': 'East Freeport', 'era': 'Old World', 'notes': ''},
    'freeportwest': {'id': 383, 'long_name': 'West Freeport', 'era': 'Old World', 'notes': ''},
    'freeportsewers': {'id': 384, 'long_name': 'Freeport Sewers', 'era': 'Old World', 'notes': ''},
    'freeportacademy': {'id': 385, 'long_name': 'Academy of Arcane Sciences', 'era': 'Prophecy of Ro', 'notes': ''},
    'freeporttemple': {'id': 386, 'long_name': 'Temple of Marr (B)', 'era': 'Prophecy of Ro', 'notes': ''},
    'freeportmilitia': {'id': 387, 'long_name': 'Freeport Militia House', 'era': 'Prophecy of Ro', 'notes': ''},
    'freeportarena': {'id': 388, 'long_name': 'Arena', 'era': 'Prophecy of Ro', 'notes': ''},
    'freeportcityhall': {'id': 389, 'long_name': 'City Hall', 'era': 'Prophecy of Ro', 'notes': ''},
    'freeporttheater': {'id': 390, 'long_name': 'Theater', 'era': 'Prophecy of Ro', 'notes': ''},
    'freeporthall': {'id': 391, 'long_name': 'Hall of Truth', 'era': 'Prophecy of Ro', 'notes': ''},
    'northro': {'id': 392, 'long_name': 'North Ro (B)', 'era': 'Old World', 'notes': ''},
    'southro': {'id': 393, 'long_name': 'South Ro (B)', 'era': 'Old World', 'notes': ''},
    'crescent': {'id': 394, 'long_name': 'Crescent Reach', 'era': 'The Serpents Spine', 'notes': ''},
    'moors': {'id': 395, 'long_name': 'Blightfire Moors', 'era': 'The Serpents Spine', 'notes': ''},
    'stonehive': {'id': 396, 'long_name': 'Stone Hive', 'era': 'The Serpents Spine', 'notes': ''},
    'mesa': {'id': 397, 'long_name': 'Gorukar Mesa', 'era': 'The Serpents Spine', 'notes': ''},
    'roost': {'id': 398, 'long_name': 'Blackfeather Roost', 'era': 'The Serpents Spine', 'notes': ''},
    'steppes': {'id': 399, 'long_name': 'The Steppes', 'era': 'The Serpents Spine', 'notes': ''},
    'icefall': {'id': 400, 'long_name': 'Icefall Glacier', 'era': 'The Serpents Spine', 'notes': ''},
    'valdeholm': {'id': 401, 'long_name': 'Valdeholm', 'era': 'The Serpents Spine', 'notes': ''},
    'frostcrypt': {'id': 402, 'long_name': 'Frostcrypt, Throne of the Shade King', 'era': 'The Serpents Spine', 'notes': ''},
    'sunderock': {'id': 403, 'long_name': 'Sunderock Springs', 'era': 'The Serpents Spine', 'notes': ''},
    'vergalid': {'id': 404, 'long_name': 'Vergalid Mines', 'era': 'The Serpents Spine', 'notes': ''},
    'direwind': {'id': 405, 'long_name': 'Direwind Cliffs', 'era': 'The Serpents Spine', 'notes': ''},
    'ashengate': {'id': 406, 'long_name': 'Ashengate, Reliquary of the Scale', 'era': 'The Serpents Spine', 'notes': ''},
    'commonlands': {'id': 408, 'long_name': 'Commonlands', 'era': 'Old World', 'notes': ''},
    'oceanoftears': {'id': 409, 'long_name': 'Ocean Of Tears', 'era': 'Old World', 'notes': ''},
    'kithforest': {'id': 410, 'long_name': 'Kithicor Forest (B)', 'era': 'Old World', 'notes': ''},
    'befallenb': {'id': 411, 'long_name': 'Befallen (B)', 'era': 'Old World', 'notes': ''},
    'innothuleb': {'id': 413, 'long_name': 'Innothule Swamp (B)', 'era': 'Old World', 'notes': ''},
    'toxxulia': {'id': 414, 'long_name': 'Toxxulia Forest', 'era': 'Old World', 'notes': ''},
    'mistythicket': {'id': 415, 'long_name': 'Misty Thicket (B)', 'era': 'Old World', 'notes': ''},
    'kattacastrum': {'id': 416, 'long_name': 'Katta Castrum', 'era': 'The Buried Sea', 'notes': ''},
    'thalassius': {'id': 417, 'long_name': 'Thalassius, the Coral Keep', 'era': 'The Buried Sea', 'notes': ''},
    'atiiki': {'id': 418, 'long_name': 'Jewel of Atiiki', 'era': 'The Buried Sea', 'notes': ''},
    'zhisza': {'id': 419, 'long_name': 'Zhisza, the Shissar Sanctuary', 'era': 'The Buried Sea', 'notes': ''},
    'silyssar': {'id': 420, 'long_name': 'Silyssar, New Chelsith', 'era': 'The Buried Sea', 'notes': ''},
    'solteris': {'id': 421, 'long_name': 'Solteris, the Throne of Ro', 'era': 'The Buried Sea', 'notes': ''},
    'barren': {'id': 422, 'long_name': 'Barren Coast', 'era': 'The Buried Sea', 'notes': ''},
    'buriedsea': {'id': 423, 'long_name': 'The Buried Sea', 'era': 'The Buried Sea', 'notes': ''},
    'jardelshook': {'id': 424, 'long_name': 'Jardels Hook', 'era': 'The Buried Sea', 'notes': ''},
    'monkeyrock': {'id': 425, 'long_name': 'Monkey Rock', 'era': 'The Buried Sea', 'notes': ''},
    'suncrest': {'id': 426, 'long_name': 'Suncrest Isle', 'era': 'The Buried Sea', 'notes': ''},
    'deadbone': {'id': 427, 'long_name': 'Deadbone Reef', 'era': 'The Buried Sea', 'notes': ''},
    'blacksail': {'id': 428, 'long_name': 'Blacksail Folly', 'era': 'The Buried Sea', 'notes': ''},
    'maidensgrave': {'id': 429, 'long_name': 'Maidens Grave', 'era': 'The Buried Sea', 'notes': ''},
    'redfeather': {'id': 430, 'long_name': 'Redfeather Isle', 'era': 'The Buried Sea', 'notes': ''},
    'shipmvp': {'id': 431, 'long_name': 'The Open Sea (A)', 'era': 'The Buried Sea', 'notes': ''},
    'shipmvu': {'id': 432, 'long_name': 'The Open Sea (B)', 'era': 'The Buried Sea', 'notes': ''},
    'shippvu': {'id': 433, 'long_name': 'The Open Sea (C)', 'era': 'The Buried Sea', 'notes': ''},
    'shipuvu': {'id': 434, 'long_name': 'The Open Sea (D)', 'era': 'The Buried Sea', 'notes': ''},
    'shipmvm': {'id': 435, 'long_name': 'The Open Sea (E)', 'era': 'The Buried Sea', 'notes': ''},
    'mechanotus': {'id': 436, 'long_name': 'Fortress Mechanotus', 'era': 'Secrets of Faydwer', 'notes': ''},
    'mansion': {'id': 437, 'long_name': 'Meldraths Majestic Mansion', 'era': 'Secrets of Faydwer', 'notes': ''},
    'steamfactory': {'id': 438, 'long_name': 'The Steam Factory', 'era': 'Secrets of Faydwer', 'notes': ''},
    'shipworkshop': {'id': 439, 'long_name': 'S.H.I.P. Workshop', 'era': 'Secrets of Faydwer', 'notes': ''},
    'gyrospireb': {'id': 440, 'long_name': 'Gyrospire Beza', 'era': 'Secrets of Faydwer', 'notes': ''},
    'gyrospirez': {'id': 441, 'long_name': 'Gyrospire Zeka', 'era': 'Secrets of Faydwer', 'notes': ''},
    'dragonscale': {'id': 442, 'long_name': 'Dragonscale Hills', 'era': 'Secrets of Faydwer', 'notes': ''},
    'lopingplains': {'id': 443, 'long_name': 'Loping Plains', 'era': 'Secrets of Faydwer', 'notes': ''},
    'hillsofshade': {'id': 444, 'long_name': 'Hills of Shade', 'era': 'Secrets of Faydwer', 'notes': ''},
    'bloodmoon': {'id': 445, 'long_name': 'Bloodmoon Keep', 'era': 'Secrets of Faydwer', 'notes': ''},
    'crystallos': {'id': 446, 'long_name': 'Crystallos, Lair of the Awakened', 'era': 'Secrets of Faydwer', 'notes': ''},
    'guardian': {'id': 447, 'long_name': 'The Mechamatic Guardian', 'era': 'Secrets of Faydwer', 'notes': ''},
    'steamfontmts': {'id': 448, 'long_name': 'Steamfont Mountains', 'era': 'Secrets of Faydwer', 'notes': ''},
    'cryptofshade': {'id': 449, 'long_name': 'Crypt of Shade', 'era': 'Secrets of Faydwer', 'notes': ''},
    'dragonscaleb': {'id': 451, 'long_name': 'Deepscars Den', 'era': 'Secrets of Faydwer', 'notes': ''},
    'oldfieldofbone': {'id': 452, 'long_name': 'Old Field of Scale', 'era': 'Seeds of Destruction', 'notes': ''},
    'oldkaesoraa': {'id': 453, 'long_name': 'Kaesora Library', 'era': 'Seeds of Destruction', 'notes': ''},
    'oldkaesorab': {'id': 454, 'long_name': 'Hatchery Wing', 'era': 'Seeds of Destruction', 'notes': ''},
    'oldkurn': {'id': 455, 'long_name': 'Old Kurns Tower', 'era': 'Seeds of Destruction', 'notes': ''},
    'oldkithicor': {'id': 456, 'long_name': 'Bloody Kithicor', 'era': 'Seeds of Destruction', 'notes': ''},
    'oldcommons': {'id': 457, 'long_name': 'Old Commonlands', 'era': 'Seeds of Destruction', 'notes': ''},
    'oldhighpass': {'id': 458, 'long_name': 'Old Highpass Hold', 'era': 'Seeds of Destruction', 'notes': ''},
    'thevoida': {'id': 459, 'long_name': 'The Void (A)', 'era': 'Seeds of Destruction', 'notes': 'Old Hub'},
    'thevoidb': {'id': 460, 'long_name': 'The Void (B)', 'era': 'Seeds of Destruction', 'notes': ''},
    'thevoidc': {'id': 461, 'long_name': 'The Void (C)', 'era': 'Seeds of Destruction', 'notes': ''},
    'thevoidd': {'id': 462, 'long_name': 'The Void (D)', 'era': 'Seeds of Destruction', 'notes': ''},
    'thevoide': {'id': 463, 'long_name': 'The Void (E)', 'era': 'Seeds of Destruction', 'notes': ''},
    'thevoidf': {'id': 464, 'long_name': 'The Void (F)', 'era': 'Seeds of Destruction', 'notes': ''},
    'thevoidg': {'id': 465, 'long_name': 'The Void (G)', 'era': 'Seeds of Destruction', 'notes': ''},
    'oceangreenhills': {'id': 466, 'long_name': 'Oceangreen Hills', 'era': 'Seeds of Destruction', 'notes': ''},
    'oceangreenvillage': {'id': 467, 'long_name': 'Oceangreen Village', 'era': 'Seeds of Destruction', 'notes': ''},
    'oldblackburrow': {'id': 468, 'long_name': 'Old Blackburrow', 'era': 'Seeds of Destruction', 'notes': ''},
    'bertoxtemple': {'id': 469, 'long_name': 'Temple of Bertoxxulous', 'era': 'Seeds of Destruction', 'notes': ''},
    'discord': {'id': 470, 'long_name': 'Korafax, Home of the Riders', 'era': 'Seeds of Destruction', 'notes': ''},
    'discordtower': {'id': 471, 'long_name': 'Citadel of the Worldslayer', 'era': 'Seeds of Destruction', 'notes': ''},
    'oldbloodfield': {'id': 472, 'long_name': 'Old Bloodfields', 'era': 'Seeds of Destruction', 'notes': ''},
    'precipiceofwar': {'id': 473, 'long_name': 'The Precipice of War', 'era': 'Seeds of Destruction', 'notes': ''},
    'olddranik': {'id': 474, 'long_name': 'City of Dranik', 'era': 'Seeds of Destruction', 'notes': ''},
    'toskirakk': {'id': 475, 'long_name': 'Toskirakk', 'era': 'Seeds of Destruction', 'notes': ''},
    'korascian': {'id': 476, 'long_name': 'Korascian Warrens', 'era': 'Seeds of Destruction', 'notes': ''},
    'rathechamber': {'id': 477, 'long_name': 'Rathe Council Chambers', 'era': 'Seeds of Destruction', 'notes': ''},
    'brellsrest': {'id': 480, 'long_name': 'Brells Rest', 'era': 'Underfoot', 'notes': ''},
    'brellstemple': {'id': 481, 'long_name': 'Brells Temple', 'era': 'Underfoot', 'notes': ''},
    'underquarry': {'id': 482, 'long_name': 'The Underquarry', 'era': 'Underfoot', 'notes': ''},
    'coolingchamber': {'id': 483, 'long_name': 'The Cooling Chamber', 'era': 'Underfoot', 'notes': ''},
    'arthicrex': {'id': 485, 'long_name': 'Arthicrex', 'era': 'Underfoot', 'notes': ''},
    'foundation': {'id': 486, 'long_name': 'The Foundation', 'era': 'Underfoot', 'notes': ''},
    'pellucid': {'id': 488, 'long_name': 'Pellucid Grotto', 'era': 'Underfoot', 'notes': ''},
    'stonesnake': {'id': 489, 'long_name': 'Volskas Husk', 'era': 'Underfoot', 'notes': ''},
    'convorteum': {'id': 491, 'long_name': 'The Convorteum', 'era': 'Underfoot', 'notes': ''},
    'brellsarena': {'id': 492, 'long_name': 'Brells Arena', 'era': 'Underfoot', 'notes': ''},
    'feerrott2': {'id': 700, 'long_name': 'The Feerrott (B)', 'era': 'House of Thule', 'notes': ''},
    'thulehouse1': {'id': 701, 'long_name': 'House of Thule', 'era': 'House of Thule', 'notes': ''},
    'thulehouse2': {'id': 702, 'long_name': 'House of Thule, Upper Floors', 'era': 'House of Thule', 'notes': ''},
    'housegarden': {'id': 703, 'long_name': 'The Grounds', 'era': 'House of Thule', 'notes': ''},
    'thulelibrary': {'id': 704, 'long_name': 'The Library', 'era': 'House of Thule', 'notes': ''},
    'well': {'id': 705, 'long_name': 'The Well', 'era': 'House of Thule', 'notes': ''},
    'fallen': {'id': 706, 'long_name': 'Erudin Burning', 'era': 'House of Thule', 'notes': ''},
    'morellcastle': {'id': 707, 'long_name': 'Morells Castle', 'era': 'House of Thule', 'notes': ''},
    'somnium': {'id': 708, 'long_name': 'Sanctum Somnium', 'era': 'House of Thule', 'notes': ''},
    'alkabormare': {'id': 709, 'long_name': 'AlKabors Nightmare', 'era': 'House of Thule', 'notes': ''},
    'miragulmare': {'id': 710, 'long_name': 'Miraguls Nightmare', 'era': 'House of Thule', 'notes': ''},
    'thuledream': {'id': 711, 'long_name': 'Fear Itself', 'era': 'House of Thule', 'notes': ''},
    'neighborhood': {'id': 712, 'long_name': 'Sunrise Hills', 'era': 'House of Thule', 'notes': ''},
    'phylactery': {'id': 713, 'long_name': 'Miraguls Phylactery', 'era': 'House of Thule', 'notes': ''},
    'morelltower': {'id': 714, 'long_name': 'Morells Tower', 'era': 'House of Thule', 'notes': ''},
    'fhalls': {'id': 998, 'long_name': 'The Forgotten Halls', 'era': 'Old World', 'notes': ''}
}

# Additional lookup dictionaries for database seeding
tradeskill_lookup = {
    55: 'Fishing',
    56: 'Make Poison',
    57: 'Tinkering',
    58: 'Research',
    59: 'Alchemy',
    60: 'Baking',
    61: 'Tailoring',
    63: 'Blacksmithing',
    64: 'Fletching',
    65: 'Brewing',
    68: 'Jewelry Making',
    69: 'Pottery',
    75: 'Quest',
}

container_lookup = {
    9: 'Medicine Bag',
    13: 'Augment',
    15: 'Oven',
    16: 'Sewing Kit',
    17: 'Forge',
    18: 'Fletching Kit',
    19: 'Brewing Barrel',
    20: 'Jewelers Kit',
    21: 'Pottery Wheel',
    22: 'Kiln',
    23: 'Key Maker',
    24: 'Wiz Research Container',
    25: 'Necro Research Container',
    26: 'Mage Research Container',
    27: 'Enchanter Research Container',
    31: 'High Elves Forge',
    32: 'Dark Elves Forge',
    33: 'Ogre Forge',
    34: 'Dwarven Forge',
    35: 'Gnomish Forge',
    36: 'Barbarian Forge',
    38: 'Iksar Forge',
    39: 'Human Forge',
    40: 'Human Forge',
    41: 'Halfling Tailoring Kit',
    42: 'Erudite Tailoring Kit',
    43: 'Wood Elf Tailoring Kit',
    44: 'Wood Elf Fletching Kit',
    45: 'Iksar Pottery Wheel',
    46: 'Tackle Box',
    47: 'Troll Forge',
    48: 'Wood Elf Forge',
    49: 'Halfling Forge',
    50: 'Erudite Forge',
    53: 'Augment',
}

race_lookup = {
    1: {'name': 'Human', 'bit_value': 1, 'abbr': 'HUM'},
    2: {'name': 'Barbarian', 'bit_value': 2, 'abbr': 'BAR'},
    3: {'name': 'Erudite', 'bit_value': 4, 'abbr': 'ERU'},
    4: {'name': 'Wood Elf', 'bit_value': 8, 'abbr': 'WEF'},
    5: {'name': 'High Elf', 'bit_value': 16, 'abbr': 'HIE'},
    6: {'name': 'Dark Elf', 'bit_value': 32, 'abbr': 'DRK'},
    7: {'name': 'Half Elf', 'bit_value': 64, 'abbr': 'HEL'},
    8: {'name': 'Dwarf', 'bit_value': 128, 'abbr': 'DWF'},
    9: {'name': 'Troll', 'bit_value': 256, 'abbr': 'TRL'},
    10: {'name': 'Ogre', 'bit_value': 512, 'abbr': 'OGR'},
    11: {'name': 'Halfling', 'bit_value': 1024, 'abbr': 'HLF'},
    12: {'name': 'Gnome', 'bit_value': 2048, 'abbr': 'GME'},
    128: {'name': 'Iksar', 'bit_value': 4096, 'abbr': 'IKS'},
    130: {'name': 'Vah Shir', 'bit_value': 8192, 'abbr': 'VSH'},
    330: {'name': 'Froglok', 'bit_value': 16384, 'abbr': 'FRG'},
    522: {'name': 'Drakkin', 'bit_value': 32768, 'abbr': 'DRK'},
}

class_lookup = {
    1: {'name': 'Warrior', 'bit_value': 1, 'abbr': 'WAR'},
    2: {'name': 'Cleric', 'bit_value': 2, 'abbr': 'CLR'},
    3: {'name': 'Paladin', 'bit_value': 4, 'abbr': 'PAL'},
    4: {'name': 'Ranger', 'bit_value': 8, 'abbr': 'RNG'},
    5: {'name': 'Shadow Knight', 'bit_value': 16, 'abbr': 'SK'},
    6: {'name': 'Druid', 'bit_value': 32, 'abbr': 'DRU'},
    7: {'name': 'Monk', 'bit_value': 64, 'abbr': 'MON'},
    8: {'name': 'Bard', 'bit_value': 128, 'abbr': 'BRD'},
    9: {'name': 'Rogue', 'bit_value': 256, 'abbr': 'ROG'},
    10: {'name': 'Shaman', 'bit_value': 512, 'abbr': 'SHM'},
    11: {'name': 'Necromancer', 'bit_value': 1024, 'abbr': 'NEC'},
    12: {'name': 'Wizard', 'bit_value': 2048, 'abbr': 'WIZ'},
    13: {'name': 'Magician', 'bit_value': 4096, 'abbr': 'MAG'},
    14: {'name': 'Enchanter', 'bit_value': 8192, 'abbr': 'ENC'},
    15: {'name': 'Beastlord', 'bit_value': 16384, 'abbr': 'BST'},
    16: {'name': 'Berserker', 'bit_value': 32768, 'abbr': 'BER'},
}

deity_lookup = {
    396: {'name': 'Agnostic', 'bit_value': 1},
    140: {'name': 'Bertoxxulous', 'bit_value': 2},
    201: {'name': 'Brell Serilis', 'bit_value': 4},
    202: {'name': 'Cazic Thule', 'bit_value': 8},
    203: {'name': 'Erollsi Marr', 'bit_value': 16},
    204: {'name': 'Bristlebane', 'bit_value': 32},
    205: {'name': 'Innoruuk', 'bit_value': 64},
    206: {'name': 'Karana', 'bit_value': 128},
    207: {'name': 'Mithaniel Marr', 'bit_value': 256},
    208: {'name': 'Prexus', 'bit_value': 512},
    209: {'name': 'Quellious', 'bit_value': 1024},
    210: {'name': 'Rallos Zek', 'bit_value': 2048},
    211: {'name': 'Rodcet Nife', 'bit_value': 4096},
    212: {'name': 'Solusek Ro', 'bit_value': 8192},
    213: {'name': 'The Tribunal', 'bit_value': 16384},
    214: {'name': 'Tunare', 'bit_value': 32768},
    215: {'name': 'Veeshan', 'bit_value': 65536},
}

aa_category_lookup = [
    {'value': '-1', 'label': 'None'},
    {'value': '0', 'label': 'Passive'},
    {'value': '1', 'label': 'Progression'},
    {'value': '2', 'label': 'Shroud Passive'},
    {'value': '3', 'label': 'Shroud Active'},
    {'value': '4', 'label': 'Veteran Reward'},
    {'value': '5', 'label': 'Tradeskill'},
    {'value': '6', 'label': 'Expendable'},
    {'value': '7', 'label': 'Racial'},
    {'value': '8', 'label': 'Initiate'},
    {'value': '9', 'label': 'EverQuest'},
]

aa_type_lookup = [
    {'value': '1', 'label': 'General'},
    {'value': '2', 'label': 'Archetype'},
    {'value': '3', 'label': 'Class'},
    {'value': '4', 'label': 'POP Advanced'},
    {'value': '5', 'label': 'POP Abilities'},
    {'value': '6', 'label': 'Gates of Discord'},
    {'value': '7', 'label': 'Omens of War'},
    {'value': '8', 'label': 'Veteran'},
    {'value': '9', 'label': 'Dragons of Norrath'},
    {'value': '10', 'label': 'Depths of Darkhollow'},
    {'value': '0', 'label': 'Not Applicable'},
]

expansion_lookup = [
    {'value': -1, 'label': 'All'},
    {'value': 0, 'label': 'Original'},
    {'value': 1, 'label': 'Kunark'},
    {'value': 2, 'label': 'Velious'},
    {'value': 3, 'label': 'Luclin'},
    {'value': 4, 'label': 'Planes of Power'},
    {'value': 5, 'label': 'Legacy of Ykesha'},
    {'value': 6, 'label': 'Lost Dungeons of Norrath'},
    {'value': 7, 'label': 'Gates of Discord'},
    {'value': 8, 'label': 'Omens of War'},
    {'value': 9, 'label': 'Dragons of Norrath'},
    {'value': 10, 'label': 'Depths of Darkhollow'},
    {'value': 11, 'label': 'Prophecy of Ro'},
    {'value': 12, 'label': 'The Serpents Spine'},
    {'value': 13, 'label': 'The Buried Sea'},
    {'value': 14, 'label': 'Secrets of Faydwer'},
    {'value': 15, 'label': 'Seeds of Destruction'},
    {'value': 16, 'label': 'Underfoot'},
    {'value': 17, 'label': 'House of Thule'},
    {'value': 18, 'label': 'Veil of Alaris'},
    {'value': 19, 'label': 'Rain of Fear'},
    {'value': 20, 'label': 'Call of the Forsaken'},
    {'value': 21, 'label': 'The Darkened Sea'},
    {'value': 22, 'label': 'The Broken Mirror'},
    {'value': 23, 'label': 'Empires of Kunark'},
    {'value': 24, 'label': 'Ring of Scale'},
    {'value': 25, 'label': 'The Burning Lands'},
    {'value': 26, 'label': 'Torment of Velious'},
    {'value': 27, 'label': 'Claws of Veeshan'},
    {'value': 28, 'label': 'Terror of Luclin'},
    {'value': 29, 'label': 'Night of Shadows'},
    {'value': 99, 'label': 'Other'},
]

spell_effect_lookup = {
    0: 'Current HP',
    1: 'AC',
    2: 'ATK',
    3: 'Movement Speed',
    4: 'STR',
    5: 'DEX',
    6: 'AGI',
    7: 'STA',
    8: 'INT',
    9: 'WIS',
    10: 'CHA',
    11: 'Attack Speed',
    12: 'Invisibility',
    13: 'See Invis',
    14: 'Water Breathing',
    15: 'Current Mana',
    16: 'NPC Frenzy',
    17: 'NPC Awareness',
    18: 'Lull',
    19: 'Add Faction',
    20: 'Blind',
    21: 'Stun',
    22: 'Charm',
    23: 'Fear',
    24: 'Stamina',
    25: 'Bind Affinity',
    26: 'Gate',
    27: 'Cancel Magic',
    28: 'Invis vs Undead',
    29: 'Invis vs Animals',
    30: 'Change Frenzy Radius',
    31: 'Mez',
    32: 'Summon Item',
    33: 'Summon Pet',
    34: 'Confuse',
    35: 'Disease Counter',
    36: 'Poison Counter',
    37: 'Detect Hostile',
    38: 'Detect Magic',
    39: 'Twincast Blocker',
    40: 'Divine Aura',
    41: 'Destroy',
    42: 'Shadow Step',
    43: 'Berserk',
    44: 'Lycanthropy',
    45: 'Vampirism',
    46: 'Resist Fire',
    47: 'Resist Cold',
    48: 'Resist Poison',
    49: 'Resist Disease',
    50: 'Resist Magic',
    51: 'Detect Traps',
    52: 'Sense Undead',
    53: 'Sense Summoned',
    54: 'Sense Animals',
    55: 'Rune',
    56: 'True North',
    57: 'Levitate',
    58: 'Illusion',
    59: 'Damage Shield',
    60: 'Transfer Item',
    61: 'Identify',
    62: 'Item ID',
    63: 'Wipe Hate List',
    64: 'Spin Target',
    65: 'Infra Vision',
    66: 'Ultra Vision',
    67: 'Eye of Zomm',
    68: 'Reclaim Pet',
    69: 'Total HP',
    70: 'Corpse Bomb',
    71: 'Necro Pet',
    72: 'Preserve Corpse',
    73: 'Bind Sight',
    74: 'Feign Death',
    75: 'Voice Graft',
    76: 'Sentinel',
    77: 'Locate Corpse',
    78: 'Absorb Magic Attack',
    79: 'Current HP Once',
    80: 'Enchant Light',
    81: 'Revive',
    82: 'Summon PC',
    83: 'Teleport',
    84: 'Toss Up',
    85: 'Weapon Proc',
    86: 'Harmony',
    87: 'Magnify Vision',
    88: 'Succor',
    89: 'Model Size',
    90: 'Cloak',
    91: 'Summon Corpse',
    92: 'Instant Hate',
    93: 'Stop Rain',
    94: 'Negate if Combat',
    95: 'Sacrifice',
    96: 'Silence',
    97: 'Mana Pool',
    98: 'Attack Speed 2',
    99: 'Root',
    100: 'Heal Over Time',
    101: 'Complete Heal',
    102: 'Fearless',
    103: 'Call Pet',
    104: 'Translocate',
    105: 'Anti-Gate',
    106: 'Summon Beast Pet',
    107: 'Alter NPC Level',
    108: 'Familiar',
    109: 'Create Item Into Bag',
    110: 'Increase Archery',
    111: 'Resist All',
    112: 'Casting Level',
    113: 'Summon Horse',
    114: 'Change Aggro',
    115: 'Hunger',
    116: 'Curse Counter',
    117: 'Magic Weapon',
    118: 'Amplification',
    119: 'Attack Speed 3',
    120: 'Heal Rate',
    121: 'Reverse DS',
    122: 'Reduce Skill',
    123: 'Screech',
    124: 'Improved Damage',
    125: 'Improved Heal',
    126: 'Spell Resist Reduction',
    127: 'Increase Spell Haste',
    128: 'Increase Spell Duration',
    129: 'Increase Range',
    130: 'Spell Hate Mod',
    131: 'Reduce Reagent Cost',
    132: 'Reduce Mana Cost',
    133: 'Focus: Stun Time Mod',
    134: 'Limit: Max Level',
    135: 'Limit: Resist',
    136: 'Limit: Target',
    137: 'Limit: Effect',
    138: 'Limit: Spell Type',
    139: 'Limit: Spell',
    140: 'Limit: Min Duration',
    141: 'Limit: Instant',
    142: 'Limit: Min Level',
    143: 'Limit: Cast Time Min',
    144: 'Limit: Cast Time Max',
    145: 'Teleport 2',
    146: 'Electricity Resist',
    147: 'Percent Heal',
    148: 'Stacking Command Block',
    149: 'Stacking Command Overwrite',
    150: 'Death Save',
    151: 'Suspend Pet',
    152: 'Temporary Pets',
    153: 'Balance HP',
    154: 'Dispel Detrimental',
    155: 'Spell Crit Damage Increase',
    156: 'Illusion Copy',
    157: 'Spell Damage Shield',
    158: 'Reflect',
    159: 'All Stats',
    160: 'Make Drunk',
    161: 'Mitigate Spell Damage',
    162: 'Mitigate Melee Damage',
    163: 'Negate Attacks',
    164: 'Appraise LDoN Chest',
    165: 'Disarm LDoN Trap',
    166: 'Unlock LDoN Chest',
    167: 'Pet Power Increase',
    168: 'Melee Mitigation',
    169: 'Critical Hit Chance',
    170: 'Spell Crit Chance',
    171: 'Crippling Blow Chance',
    172: 'Avoid Melee Chance',
    173: 'Riposte Chance',
    174: 'Dodge Chance',
    175: 'Parry Chance',
    176: 'Dual Wield Chance',
    177: 'Double Attack Chance',
    178: 'Melee Lifetap',
    179: 'All Instrument Mod',
    180: 'Resist Spell Chance',
    181: 'Resist Fear Chance',
    182: 'Hundred Hands',
    183: 'Melee Skill Check',
    184: 'Hit Chance',
    185: 'Damage Modifier',
    186: 'Min Damage Mod',
    187: 'Balance Mana',
    188: 'Increase Block Chance',
    189: 'CurrentEndurance',
    190: 'Endurance Pool',
    191: 'Amnesia',
    192: 'Hate',
    193: 'Skill Attack',
    194: 'Fading Memories',
    195: 'Stun Resist',
    196: 'Strike Through',
    197: 'Skill Damage Taken',
    198: 'Current Endurance Once',
    199: 'Taunt',
    200: 'Proc Chance',
    201: 'Ranged Proc',
    202: 'Illusion Other',
    203: 'Mass Group Buff',
    204: 'Group Fear Immunity',
    205: 'Rampage',
    206: 'AE Taunt',
    207: 'Flesh to Bone',
    208: 'Purge Poison',
    209: 'Dispel Beneficial',
    210: 'Pet Shield',
    211: 'AE Melee',
    212: 'Frenzied Devastation',
    213: 'Pet Max HP',
    214: 'Max HP Change',
    215: 'Pet Avoidance',
    216: 'Accuracy',
    217: 'Head Shot',
    218: 'Pet Critical Hit',
    219: 'Slay Undead',
    220: 'Skill Damage Amount',
    221: 'Packrat',
    222: 'Block Behind',
    223: 'Double Riposte',
    224: 'Give Double Riposte',
    225: 'Give Double Attack',
    226: 'Two Hand Bash',
    227: 'Reduce Skill Timer',
    228: 'Reduce Fall Damage',
    229: 'Persistent Casting',
    230: 'Extended Shielding',
    231: 'Stun Bash Chance',
    232: 'Divine Save',
    233: 'Metabolism',
    234: 'Reduce Apply Poison Time',
    235: 'Channel Chance Spells',
    236: 'Free Pet',
    237: 'Give Pet Group Target',
    238: 'Illusion Persistence',
    239: 'Feigned Cast on Chance',
    240: 'String Unbreakable',
    241: 'Improve Reclaim Energy',
    242: 'Increase Chance Memwipe',
    243: 'Charm Break Chance',
    244: 'Root Break Chance',
    245: 'Trap Circumvention',
    246: 'Set Breath Level',
    247: 'Raise Skill Cap',
    248: 'Secondary Forte',
    249: 'Secondary Damage Increase',
    250: 'Spell Proc Chance',
    251: 'Consume Projectile',
    252: 'Frontal Backstab Chance',
    253: 'Frontal Backstab Min Damage',
    254: 'Blank',
    255: 'Shield Duration',
    256: 'Shroud of Stealth',
    257: 'Pet Discipline',
    258: 'Triple Backstab',
    259: 'Combat Stability',
    260: 'Add Singing Mod',
    261: 'Song Mod Cap',
    262: 'Raise Stat Cap',
    263: 'Tradeskill Mastery',
    264: 'Hastened AA Skill',
    265: 'Mastery of Past',
    266: 'Extra Attack Chance',
    267: 'Add Pet Command',
    268: 'Reduce Tradeskill Fail',
    269: 'Max Bind Wound',
    270: 'Bard Song Range',
    271: 'Base Movement Speed',
    272: 'Casting Level 2',
    273: 'Critical DoT Chance',
    274: 'Critical Heal Chance',
    275: 'Critical Mend',
    276: 'Ambidexterity',
    277: 'Unfailing Divinity',
    278: 'Finishing Blow',
    279: 'Flurry',
    280: 'Pet Flurry',
    281: 'Feigned Minion',
    282: 'Improved Bind Wound',
    283: 'Double Special Attack',
    284: 'LoH Set Heal',
    285: 'Nimble Evasion',
    286: 'Focus: Damage Amount',
    287: 'Spell Duration Increase by Tick',
    288: 'Skill Attack Proc',
    289: 'Cast on Fade Effect',
    290: 'Increase Run Speed Cap',
    291: 'Purify',
    292: 'Strike Through 2',
    293: 'Frontal Stun Resist',
    294: 'Critical Spell Chance',
    295: 'Reduce Timer Special',
    296: 'Focus: Spell Vulnerability',
    297: 'Focus: Damage Amount Incoming',
    298: 'Change Height',
    299: 'Wake the Dead',
    300: 'Doppelganger',
    301: 'Archery Damage Modifier',
    302: 'Focus: Damage Percent Crit',
    303: 'Focus: Damage Amount Crit',
    304: 'Offhand Riposte Fail',
    305: 'Mitigate Damage Shield',
    306: 'Army of the Dead',
    307: 'Appraisal',
    308: 'Suspend Minion',
    309: 'Gate Casters Bindpoint',
    310: 'Reduce Reuse Timer',
    311: 'Limit: Combat Skills',
    312: 'Sanctuary',
    313: 'Forage Additional Items',
    314: 'Invisibility 2',
    315: 'Invis vs Undead 2',
    316: 'Improved Invis Animals',
    317: 'Item HP Regen Cap Increase',
    318: 'Item Mana Regen Cap Increase',
    319: 'Critical Heal Over Time',
    320: 'Shield Block',
    321: 'Reduce Hate',
    322: 'Gate to Home City',
    323: 'Defensive Proc',
    324: 'HP to Mana',
    325: 'No Break AE Sneak',
    326: 'Spell Slot Increase',
    327: 'Mystical Attune',
    328: 'Delay Death',
    329: 'Mana Absorb Percent Damage',
    330: 'Critical Damage Mod',
    331: 'Salvage',
    332: 'Summon to Corpse',
    333: 'Cast on Rune Fade Effect',
    334: 'Bard AE DoT',
    335: 'Block Next Spell Focus',
    336: 'Illusionary Target',
    337: 'Percent XP Increase',
    338: 'Summon and Resurrect All Corpses',
    339: 'Trigger on Cast',
    340: 'Spell Trigger',
    341: 'Item Attack Cap Increase',
    342: 'Immune Fleeing',
    343: 'Interrupt Casting',
    344: 'Channel Chance Items',
    345: 'Assassinate Level',
    346: 'Head Shot Level',
    347: 'Double Ranged Attack',
    348: 'Limit: Mana Min',
    349: 'Shield Equip Damage Mod',
    350: 'Mana Burn',
    351: 'Persistent Effect',
    352: 'Increase Trap Count',
    353: 'Additional Aura',
    354: 'Deactivate All Traps',
    355: 'Learn Trap',
    356: 'Change Trigger Type',
    357: 'Focus: Mute',
    358: 'Current Mana Once',
    359: 'Passive Sense Trap',
    360: 'Proc on Kill Shot',
    361: 'Spell on Death',
    362: 'Potion Belt Slots',
    363: 'Bandolier Slots',
    364: 'Triple Attack Chance',
    365: 'Proc on Spell Kill Shot',
    366: 'Group Shielding',
    367: 'Set Body Type',
    368: 'Faction Mod',
    369: 'Corruption Counter',
    370: 'Resist Corruption',
    371: 'Attack Speed 4',
    372: 'Forage Skill',
    373: 'Cast on Fade Effect Always',
    374: 'Apply Effect',
    375: 'DoT Crit Damage Increase',
    376: 'Fling',
    377: 'Cast on Fade Effect NPC',
    378: 'Spell Effect Resist Chance',
    379: 'Shadow Step Directional',
    380: 'Knockdown',
    381: 'Knock Toward Caster',
    382: 'Negate Spell Effect',
    383: 'Sympathetic Proc',
    384: 'Leap',
    385: 'Limit: Spell Group',
    386: 'Cast on Curer',
    387: 'Cast on Cure',
    388: 'Summon Corpse Zone',
    389: 'Focus: Timer Refresh',
    390: 'Focus: Timer Lockout',
    391: 'Limit: Mana Max',
    392: 'Focus: Heal Amt',
    393: 'Focus: Heal Percent Incoming',
    394: 'Focus: Heal Amt Incoming',
    395: 'Focus: Heal Percent Crit Incoming',
    396: 'Focus: Heal Amt Crit',
    397: 'Pet Melee Mitigation',
    398: 'Swarm Pet Duration',
    399: 'Focus: Twincast',
    400: 'Heal Group from Mana',
    401: 'Mana Drain with Dmg',
    402: 'Endurance Drain with Dmg',
    403: 'Limit: Spell Class',
    404: 'Limit: Spell Subclass',
    405: 'Two Hand Blunt Block',
    406: 'Cast on Num Hit Fade',
    407: 'Cast on Focus Effect',
    408: 'Limit: HP Percent',
    409: 'Limit: Mana Percent',
    410: 'Limit: Endurance Percent',
    411: 'Limit: Class',
    412: 'Limit: Race',
    413: 'Focus: Base Effects',
    414: 'Limit: Casting Skill',
    415: 'Limit: Item Class',
    416: 'AC v2',
    417: 'Mana Regen v2',
    418: 'Skill Damage Amount 2',
    419: 'Add Melee Proc',
    420: 'Focus: Limit Use',
    421: 'Focus: Increase Num Hits',
    422: 'Limit: Use Min',
    423: 'Limit: Use Type',
    424: 'Gravity Effect',
    425: 'Display',
    426: 'Increase Ext Target Window',
    427: 'Skill Proc',
    428: 'Limit to Skill',
    429: 'Skill Proc Success',
    430: 'Post Effect',
    431: 'Post Effect Data',
    432: 'Expand Max Active Trophy Benefits',
    433: 'Critical DoT Decay',
    434: 'Critical Heal Decay',
    435: 'Critical Regen Decay',
    436: 'Beneficial Countdown Hold',
    437: 'Teleport to Anchor',
    438: 'Translocate to Anchor',
    439: 'Assassinate',
    440: 'Finishing Blow Level',
    441: 'Distance Removal',
    442: 'Trigger on Req Target',
    443: 'Trigger on Req Caster',
    444: 'Improved Taunt',
    445: 'Add Merc Slot',
    446: 'A Stacker',
    447: 'B Stacker',
    448: 'C Stacker',
    449: 'D Stacker',
    450: 'Mitigate DoT Damage',
    451: 'Melee Threshold Guard',
    452: 'Spell Threshold Guard',
    453: 'Trigger Melee Threshold',
    454: 'Trigger Spell Threshold',
    455: 'Add Hate Percent',
    456: 'Add Hate Over Time Percent',
    457: 'Resource Tap',
    458: 'Faction Mod Percent',
    459: 'Damage Modifier 2',
    460: 'Limit: Override Not Focusable',
    461: 'Improved Damage 2',
    462: 'Focus: Damage Amount 2',
    463: 'Shield Target',
    464: 'PC Pet Rampage',
    465: 'PC Pet AE Rampage',
    466: 'Player Pet Flurry Chance',
    467: 'DS Mitigation Amount',
    468: 'DS Mitigation Percent',
    469: 'Chance Best in Spell Group',
    470: 'Trigger Best in Spell Group',
    471: 'Double Melee Round',
    472: 'Buy AA Rank',
    473: 'Double Backstab Front',
    474: 'Pet Crit Melee Damage Percent Owner',
    475: 'Trigger Spell Non-Item',
    476: 'Weapon Stance',
    477: 'Hatelist to Top Index',
    478: 'Hatelist to Tail Index',
    479: 'Limit: Value Min',
    480: 'Limit: Value Max',
    481: 'Focus: Cast Spell on Land',
    482: 'Skill Base Damage Mod',
    483: 'Focus: Spell Damage Percent Incoming PC',
    484: 'Focus: Spell Damage Amount Incoming PC',
    485: 'Limit: Caster Class',
    486: 'Limit: Same Caster',
    487: 'Extend Tradeskill Cap',
    488: 'Defender Melee Force Percent PC',
    489: 'Worn Endurance Regen Cap',
    490: 'Limit: Reuse Time Min',
    491: 'Limit: Reuse Time Max',
    492: 'Limit: Endurance Min',
    493: 'Limit: Endurance Max',
    494: 'Pet Add Attack',
    495: 'Limit: Duration Max',
    496: 'Critical Melee Damage Mod Max',
    497: 'Limit: Focus Cast Proc No Bypass',
    498: 'Add Extra Attack Percent 1H PRI',
    499: 'Add Extra Attack Percent 1H SEC',
    500: 'Focus: Cast Time Mod 2',
    501: 'Focus: Cast Time Amount',
    502: 'Fearstun',
    503: 'Melee Damage Position Mod',
    504: 'Melee Damage Position Amount',
    505: 'Damage Taken Position Mod',
    506: 'Damage Taken Position Amount',
    507: 'Focus: Amplify Mod',
    508: 'Focus: Amplify Amount',
    509: 'Health Transfer',
    510: 'Focus: Resist Incoming',
    511: 'Limit: Focus Timer Min',
    512: 'Proc Timer Modifier',
    513: 'Mana Max Percent',
    514: 'Endurance Max Percent',
    515: 'AC Avoidance Max Percent',
    516: 'AC Mitigation Max Percent',
    517: 'Attack Offense Max Percent',
    518: 'Attack Accuracy Max Percent',
    519: 'Luck Amount',
    520: 'Luck Percent',
    521: 'Endurance Absorb Percent Damage',
    522: 'Instant Mana Percent',
    523: 'Instant Endurance Percent',
    524: 'Duration HP Percent',
    525: 'Duration Mana Percent',
    526: 'Duration Endurance Percent',
}
